on:
  push:
    branches: ['master']
  pull_request:
name: build
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22.7, 1.23.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Test
      run: go test -covermode atomic -coverprofile='${{ matrix.os }}-${{ matrix.go-version }}.cov' ./...
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@cfd0633edbd2411b532b808ba7a8b5e04f76d2c8
      with:
        file: '${{ matrix.os }}-${{ matrix.go-version }}.cov'
        parallel: true
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@cfd0633edbd2411b532b808ba7a8b5e04f76d2c8
      with:
        parallel-finished: true
