on: [pull_request]
name: lint

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: golangci-lint
        uses: golangci/golangci-lint-action@818ec4d51a1feacefc42ff1b3ec25d4962690f39
        with:
          only-new-issues: true
          version: v1.62
