name: Docgen and go fmt

on:
  workflow_dispatch:
  push:
    branches: ['master']
  pull_request:

jobs:
  docgen:
    name: Verify Docgen
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version: '1.21.x'
      - run: ./scripts/verify-docs.sh
  fmt:
    name: Verify go fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version: '1.21.x'
      - run: test -z $(go fmt ./...)
