name: Docgen and go fmt

on:
  workflow_dispatch:
  push:
    branches: ['master']
  pull_request:

jobs:
  docgen:
    name: Verify Docgen
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
      - run: ./scripts/verify-docs.sh
  fmt:
    name: Verify go fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
      - run: test -z $(go fmt ./...)
